site_name: Metrix
repo_name: cgarciae/metrix
repo_url: https://github.com/cgarciae/metrix
site_url: https://cgarciae.github.io/metrix
nav:
- Metrix: index.md
- API Reference:
    Loss: api/Loss.md
    Losses: api/Losses.md
    LossesAndMetrics: api/LossesAndMetrics.md
    Metric: api/Metric.md
    Metrics: api/Metrics.md
    Named: api/Named.md
    losses:
      CosineSimilarity: api/losses/CosineSimilarity.md
      Crossentropy: api/losses/Crossentropy.md
      Huber: api/losses/Huber.md
      Loss: api/losses/Loss.md
      MeanAbsoluteError: api/losses/MeanAbsoluteError.md
      MeanAbsolutePercentageError: api/losses/MeanAbsolutePercentageError.md
      MeanSquaredError: api/losses/MeanSquaredError.md
      MeanSquaredLogarithmicError: api/losses/MeanSquaredLogarithmicError.md
      Reduction: api/losses/Reduction.md
      cosine_similarity: api/losses/cosine_similarity.md
      crossentropy: api/losses/crossentropy.md
      huber: api/losses/huber.md
      mean_absolute_error: api/losses/mean_absolute_error.md
      mean_absolute_percentage_error: api/losses/mean_absolute_percentage_error.md
      mean_squared_error: api/losses/mean_squared_error.md
      mean_squared_logarithmic_error: api/losses/mean_squared_logarithmic_error.md
    metrics:
      Accuracy: api/metrics/Accuracy.md
      AuxLosses: api/metrics/AuxLosses.md
      AuxMetrics: api/metrics/AuxMetrics.md
      Losses: api/metrics/Losses.md
      LossesAndMetrics: api/metrics/LossesAndMetrics.md
      MAE: api/metrics/MAE.md
      MSE: api/metrics/MSE.md
      Mean: api/metrics/Mean.md
      MeanAbsoluteError: api/metrics/MeanAbsoluteError.md
      MeanSquareError: api/metrics/MeanSquareError.md
      Metric: api/metrics/Metric.md
      Metrics: api/metrics/Metrics.md
      Reduce: api/metrics/Reduce.md
      Reduction: api/metrics/Reduction.md
    regularizers:
      L1: api/regularizers/L1.md
      L1L2: api/regularizers/L1L2.md
      L2: api/regularizers/L2.md
extra:
  search:
    language: en
  social:
  - icon: octicons/mark-github-16
    link: https://github.com/cgarciae
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/cgarciae88
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/cgarciae
theme:
  name: material
  favicon: images/favicon.png
  icon:
    logo: fontawesome/solid/infinity
    repo: octicons/mark-github-16
markdown_extensions:
- pymdownx.arithmatex
- admonition
- pymdownx.highlight
- pymdownx.superfences
- codehilite:
    guess_lang: false
    use_pygments: true
    noclasses: true
    pygments_style: default
plugins:
- search
- mkdocs-jupyter
- mkdocstrings:
    watch:
    - metrix
extra_javascript:
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
